model_list:
  - model_name: gemini-3.1-pro
    litellm_params:
      model: vertex_ai/gemini-3.1-pro-preview
      vertex_project: "janitor-api-or-wtv"
      vertex_location: "global"

  - model_name: gemini-3.8-flash
    litellm_params:
      model: vertex_ai/gemini-3.8-flash 
      vertex_project: "janitor-api-or-wtv"
      vertex_location: "global" 

  - model_name: opus-snowflake
    litellm_params:
      model: snowflake/claude-opus-5-5
      api_base: os.environ/SNOWFLAKE_API_BASE
      api_key: os.environ/SNOWFLAKE_API_KEY

    - model_name: opus-direct
    litellm_params:
      model: openai/claude-opus-5-5
      api_base: os.environ/SNOWFLAKE_CHAT_BASE
      api_key: os.environ/SNOWFLAKE_PAT_RAW
      extra_headers:
        X-Snowflake-Authorization-Token-Type: PROGRAMMATIC_ACCESS_TOKEN
      
 
litellm_settings:
  drop_params: true
  cors: true
