model_list:
  - model_name: gemini-3.1-pro
    litellm_params:
      model: vertex_ai/gemini-3.1-pro-preview
      vertex_project: "roleplaying-488810"
      vertex_location: "global"

  - model_name: claude-opus-4-7
    litellm_params:
      model: vertex_ai/claude-opus-4-7 
      vertex_project: "roleplaying-488810"
      vertex_location: "global" 
 
litellm_settings:
  drop_params: true
  cors: true
