model_list:
  - model_name: gemini-3.1-pro
    litellm_params:
      model: vertex_ai/gemini-3.1-pro-preview
      vertex_project: "janitor-api-or-wtv"
      vertex_location: "global"

  - model_name: gemini-3.7-flash
    litellm_params:
      model: vertex_ai/gemini-3.7-flash 
      vertex_project: "janitor-api-or-wtv"
      vertex_location: "global" 
 
litellm_settings:
  drop_params: true
  cors: true
